### PR TITLE
Test/jy

### LINKED ISSUE #30: frontend/Filter Sort Restaurants

### PR DESCRIPTION
**Pull request by JasonSYuen**
## Changes
_List Changes Introduced by this PR_
1. 2 new hooks, isDropdownOpen and sortBy  -is drop checks if the drop down menu is open or not sort by determines what the user is sorting by
2. button around the SVG image to turn it into a drop down menu
3. Function that sorts 
## Purpose
 Filter Restaurants has been introduced allowing users to filter based on price asc, desc, and food type

## Approach
_How does this change address the problem?_
Fixes the issue of not being able to sort restaurants based on tags

_If this closes an issue, reference the issue here. If it doesn't, remove this line_
Closes #030

Note: Ratings is written in but is not implemented. Should be included when ratings are included in the database

### CODE REVIEW

**Review by sorayaboza — APPROVED** [review]
Great work!

**Comment by davidxiong117** [comment]
I would suggest waiting to merge this until [https://github.com/Bay-Valley-Tech-Code-Academy/EatsInReach/pull/57](url) is successfully reviewed and merged to dev.

**Comment by davidxiong117** [comment]
Double check for any merge conflicts before merging! there's been a few updates to dev since.

**Comment by GuiH823** [comment]
Nice! Make sure to merge with dev, should be automatic

**Review by GuiH823 — APPROVED** [review]
Looks good!

**Pull request merged**
